version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brolga
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s

  brolga:
    image: smfsysops/brolga:1.0.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/brolga"
      SECRET_KEY_BASE: 9WAXlLWMehEKcGi6o/SJjrPgls7X+vswSxdBWiIuuXRNvNEyyH50esphx+vjQoHx
      # Change the following to accomodate your needs
      SLACK_NOTIFIER_ENABLED: "true"
      SLACK_NOTIFIER_USERNAME: "Brolga"
      SLACK_NOTIFIER_CHANNEL: "#sysops"
      DEFAULT_ADMIN_EMAIL: "<your admin email>"
      DEFAULT_ADMIN_PASSWORD: "<your admin password>"
      POSTMARK_API_KEY: "<you api key>"
      POSTMARK_MESSAGE_STREAM: "<your stream>"
      HOST: "<your host>"  # i.e. brolga.mycompany.com


volumes:
  db-data:
