version: '3.9'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brolga_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s

  brolga_dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      SECRET_KEY_BASE: 9WAXlLWMehEKcGi6o/SJjrPgls7X+vswSxdBWiIuuXRNvNEyyH50esphx+vjQoHx
      DATABASE_URL: postgres://postgres:postgres@postgres/brolga_dev
      HOST: localhost
      RUNNING_IN_DOCKER: "true"
    ports:
      - "4000:4000"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      db:
        condition: service_healthy
    working_dir: /usr/src/app
    stdin_open: true
    tty: true

volumes:
  db-data:
