import Config

# Configure your database
config :brolga, Brolga.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "db",
  database: "brolga_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :brolga_web, BrolgaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "rZgObgT7SQhQCXNm7/hrTegU1xtDTsqy9sFWaFYElUycbAgUGu9FUrq9HtGSkCJn",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :brolga_web, BrolgaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/brolga_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :brolga_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# In case you want to test a notifier in particular, configure it below
# You most likely don't want to commit them, so use the `local.exs` config
# file, which is ignored by git

config :brolga, :email_notifier,
  enabled: true,
  from: {
    "Exemple admin",
    "admin@example.com"
  },
  to: {
    "Example recipient",
    "recipient@example.com"
  }

# config :brolga, :slack_notifier,
#   enabled: false,
#   webhook_url: "",
#   username: "Brolga",
#   channel: "#sysops"

config :brolga, :auth,
  default_admin_email: "dev-admin@brolga.test",
  default_admin_password: "dev-admin-password"

if File.exists?("config/local.exs") do
  import_config "local.exs"
end
